server:
  port: 8088
  servlet:
    context-path: /

spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://47.112.24.164:3306/carrent?useUnicode=true&characterEncoding=utf8&useSSL=false&failOverReadOnly=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: root@Chris
      minimum-idle: 5
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
  mvc:
    static-path-pattern: /**
    view:
      suffix: .html
      prefix: classpath:/resource/templates
  resources:
    static-locations: classpath:/resource/templates,classpath:/resource/static

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto